version: '3.9'
services:
  postgres:
    image: postgres
    container_name: postgresql
    ports:
      - "5432:5432"
    environment:
      - TZ=America/Cuiaba
      - POSTGRES_USER=${DB_USERNAME:-username}
      - POSTGRES_PASSWORD=${DB_PASSWORD:-userpass}
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: